name: open_money
description: Open Money App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1
  shared_preferences: ^2.0.15
  http: ^0.13.4
  intl: ^0.17.0
  fl_chart: ^0.55.0
  flutter_svg: ^1.1.1+1
  rflutter_alert: ^2.0.4
  stacked: ^2.3.14
  webview_flutter: ^4.0.1
  video_player: ^2.4.5
  youtube_player_flutter: ^8.1.0
  dropdown_button2: ^1.7.1
  styled_text: ^5.1.0
  percent_indicator: ^4.2.2
  url_launcher: ^6.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
